# Generated by Django 5.2.5 on 2025-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('special', 'Special'), ('umrah', 'Umrah'), ('dubai', 'Dubai')], default='special', max_length=50),
        ),
    ]
