# Generated by Django 5.2.5 on 2025-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('mashxur', 'Mashxur'), ('ziyorat', 'Ziyorat'), ('hordiq', 'Hordiq'), ('davolanish', 'Davolanish'), ('visa', 'Visa')], default='mashxur', max_length=20),
        ),
    ]
