# Generated by Django 5.2.5 on 2025-08-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_image_alter_tour_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('mashxur', 'Mashxur'), ('ziyorat', 'Ziyorat'), ('hordiq', 'Hordiq'), ('davolanish', 'Davolanish'), ('visa', 'Visa')], max_length=20)),
                ('photo', models.ImageField(upload_to='tours/')),
            ],
        ),
    ]
